/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf
Author: silvercrow101 (https://sketchfab.com/silvercrow101)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/space-boi-f6a8c6a6727b4f2cb020c8b50bb2ee60
Title: space boi
*/

import React, { useLayoutEffect, useRef } from 'react'
import { useGLTF, useScroll } from '@react-three/drei'
import gsap from 'gsap';
import { useFrame } from '@react-three/fiber';

export const FLOR_HEIGHT = 2.3;
export const NB_FLOORS = 3;

export function Space(props) {
  const { nodes, materials } = useGLTF('./models/scene.gltf')
  const ref = useRef()
  const tl = useRef()

  const waves1 = useRef()
  const waves2 = useRef()
  const waves3 = useRef()
  const boy_model = useRef()

  const scroll = useScroll()

  useFrame(() => {
    tl.current.seek(scroll.offset * tl.current.duration())
  })

  useLayoutEffect(() => {

    tl.current = gsap.timeline()

    // Анимация

    tl.current.to(
      ref.current.position,
      {
        duration: 2,
        y: -FLOR_HEIGHT * (NB_FLOORS - 1),
      },
      0
    )

    // Модели

    tl.current.from(
      boy_model.current.position,
      {
        duration: 0.5,
        x: -200,
      },
      0
    )

    tl.current.from(
      waves1.current.position,
      {
        duration: 0.5,
        x: -200,
      },
      0
    )

    tl.current.from(
      waves2.current.position,
      {
        duration: 0.5,
        x: -200,
      },
      0
    )
    
    tl.current.from(
      waves3.current.position,
      {
        duration: 0.5,
        x: -100,
      },
      0
    )



    // Угол обзора

    tl.current.to(
      ref.current.rotation,
      {
        duration: 1, x: 0, y: Math.PI / 2, z: 1
      },
      0
    )

    tl.current.to(
      ref.current.rotation,
      {
        duration: 1, x: 0, y: Math.PI / 6, z: 0.5
      },
      1
    )

  }, [])

  return (
    <group {...props} dispose={null} ref={ref}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100} ref={boy_model}>
            <mesh geometry={nodes.body_Material001_0.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.body_Material002_0.geometry} material={materials['Material.002']} />
        </group>
        <group position={[-357.4, 392.65, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={39.71}>
            <mesh geometry={nodes.Sphere002_Material001_0.geometry} material={materials['Material.001']}/>
            <mesh geometry={nodes.Sphere002_Material002_0.geometry} material={materials['Material.002']}/>
        </group>
        <group position={[199.63, 566.88, -221]} rotation={[-Math.PI / 2, 0, 0]} scale={39.71}>
          <mesh geometry={nodes.Sphere007_Material001_0.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Sphere007_Material002_0.geometry} material={materials['Material.002']} />
        </group>
        <mesh geometry={nodes.waves_Material002_0.geometry} material={materials['Material.002']} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 1.89]} ref={waves1}/>
        <mesh geometry={nodes.waves1_Material002_0.geometry} material={materials['Material.002']} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 1.89]} ref={waves2}/>
        <mesh geometry={nodes.waves2_Material002_0.geometry} material={materials['Material.002']} position={[92.46, 15.53, 2.11]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 1.89]} ref={waves3}/>
        <mesh geometry={nodes.particles_Material002_0.geometry} material={materials['Material.002']} position={[489.69, 793.81, 355.29]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={20.41} />
        <mesh geometry={nodes.Sphere_Material001_0.geometry} material={materials['Material.001']} position={[375.47, 427.95, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={62.4} />
        <mesh geometry={nodes.Sphere001_Material002_0.geometry} material={materials['Material.002']} position={[375.47, 427.95, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={60.32} />
        <mesh geometry={nodes.Sphere004_Material002_0.geometry} material={materials['Material.002']} position={[375.47, 427.95, 0]} rotation={[-0.69, 0, 0]} scale={[104.13, 81.61, 0]} />
        <mesh geometry={nodes.Sphere005_Material001_0.geometry} material={materials['Material.001']} position={[-341.99, 460.2, -117.03]} rotation={[-Math.PI / 2, 0, 0]} scale={62.4} />
        <mesh geometry={nodes.Sphere006_Material002_0.geometry} material={materials['Material.002']} position={[-341.99, 460.2, -117.03]} rotation={[-Math.PI / 2, 0, 0]} scale={60.32} />
        <mesh geometry={nodes.Sphere009_Material002_0.geometry} material={materials['Material.002']} position={[507.52, 667.59, -214.48]} rotation={[-Math.PI / 2, 0, 0]} scale={16.88} />
        <mesh geometry={nodes.Sphere010_Material002_0.geometry} material={materials['Material.002']} position={[-287.44, 585.79, -311.86]} rotation={[-Math.PI / 2, 0, 0]} scale={16.88} />
        <mesh geometry={nodes.Sphere011_Material002_0.geometry} material={materials['Material.002']} position={[-553.46, 331.07, -379.07]} rotation={[-Math.PI / 2, 0, 0]} scale={11.44} />
        <mesh geometry={nodes.Cube_Material001_0.geometry} material={materials['Material.001']} position={[0, -101.67, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[1120.01, 1120.01, 100]} />
        <mesh geometry={nodes.Sphere003_Material002_0.geometry} material={materials['Material.002']} position={[-357.4, 392.65, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={41.07}/>
        <mesh geometry={nodes.Sphere008_Material002_0.geometry} material={materials['Material.002']} position={[199.63, 566.88, -221]} rotation={[-Math.PI / 2, 0, 0]} scale={41.07} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/scene.gltf')

export default Space
